#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MainMobileDevProject.Resource", IsApplication=true)]

namespace MainMobileDevProject
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int com_facebook_auxiliary_view_position = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int com_facebook_confirm_logout = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int com_facebook_foreground_color = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int com_facebook_horizontal_alignment = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int com_facebook_is_cropped = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int com_facebook_login_text = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int com_facebook_logout_text = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int com_facebook_object_id = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int com_facebook_object_type = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int com_facebook_preset_size = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int com_facebook_style = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int com_facebook_tooltip_mode = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_blue = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_button_background_color = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_button_background_color_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_button_background_color_pressed = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_button_like_background_color_selected = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_button_login_silver_background_color = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_button_login_silver_background_color_pressed = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_button_send_background_color = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_button_send_background_color_pressed = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_likeboxcountview_border_color = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_likeboxcountview_text_color = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_likeview_text_color = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_share_button_text_color = 2131099660;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_likeboxcountview_border_radius = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_likeboxcountview_border_width = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int com_facebook_likeboxcountview_caret_height = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_likeboxcountview_caret_width = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_likeboxcountview_text_padding = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int com_facebook_likeboxcountview_text_size = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int com_facebook_likeview_edge_padding = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int com_facebook_likeview_internal_padding = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int com_facebook_likeview_text_size = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int com_facebook_profilepictureview_preset_size_large = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int com_facebook_profilepictureview_preset_size_small = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int com_facebook_share_button_compound_drawable_padding = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int com_facebook_share_button_padding_bottom = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_share_button_padding_left = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_share_button_padding_right = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_share_button_padding_top = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_share_button_text_size = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_tooltip_horizontal_padding = 2131165202;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonCreateStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignInStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonSignUpStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_like_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_like_icon_selected = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_login_silver_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_send_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_send_icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_close = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_profile_picture_blank_portrait = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_profile_picture_blank_square = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_tooltip_black_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_tooltip_black_bottomnub = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_tooltip_black_topnub = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_tooltip_black_xout = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_tooltip_blue_background = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_tooltip_blue_bottomnub = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_tooltip_blue_topnub = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_tooltip_blue_xout = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int edit_text_style = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_new = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_action_overflow = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_action_person = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_action_search = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int mail4_small = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int messenger_bubble_large_blue = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int messenger_bubble_large_white = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int messenger_bubble_small_blue = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int messenger_bubble_small_white = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int messenger_button_blue_bg_round = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int messenger_button_blue_bg_selector = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int messenger_button_send_round_shadow = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int messenger_button_white_bg_round = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int messenger_button_white_bg_selector = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int plus = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ProgressBarStyle = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int sampleBackground = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int SignUpStyle = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int xiconsmall = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int xs = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a004e
			public const int add = 2131361870;
			
			// aapt resource value: 0x7f0a000c
			public const int automatic = 2131361804;
			
			// aapt resource value: 0x7f0a0006
			public const int bottom = 2131361798;
			
			// aapt resource value: 0x7f0a0003
			public const int box_count = 2131361795;
			
			// aapt resource value: 0x7f0a0032
			public const int btnAdd = 2131361842;
			
			// aapt resource value: 0x7f0a004c
			public const int btnAddAlbum = 2131361868;
			
			// aapt resource value: 0x7f0a003d
			public const int btnConverttoBase64 = 2131361853;
			
			// aapt resource value: 0x7f0a003f
			public const int btnConverttoImg = 2131361855;
			
			// aapt resource value: 0x7f0a0029
			public const int btnCreateContact = 2131361833;
			
			// aapt resource value: 0x7f0a004a
			public const int btnDeleteAlbum = 2131361866;
			
			// aapt resource value: 0x7f0a001a
			public const int btnDialogAddAlbum = 2131361818;
			
			// aapt resource value: 0x7f0a001d
			public const int btnDialogConfirmPhoto = 2131361821;
			
			// aapt resource value: 0x7f0a0024
			public const int btnDialogEmail = 2131361828;
			
			// aapt resource value: 0x7f0a0020
			public const int btnDialogLogin = 2131361824;
			
			// aapt resource value: 0x7f0a0034
			public const int btnFbLoginMain = 2131361844;
			
			// aapt resource value: 0x7f0a0036
			public const int btnGetEmail = 2131361846;
			
			// aapt resource value: 0x7f0a0025
			public const int btnOpenGallery = 2131361829;
			
			// aapt resource value: 0x7f0a0039
			public const int btnSignIn = 2131361849;
			
			// aapt resource value: 0x7f0a003b
			public const int btnSignUp = 2131361851;
			
			// aapt resource value: 0x7f0a0049
			public const int btnStar = 2131361865;
			
			// aapt resource value: 0x7f0a0004
			public const int button = 2131361796;
			
			// aapt resource value: 0x7f0a0009
			public const int center = 2131361801;
			
			// aapt resource value: 0x7f0a0014
			public const int com_facebook_body_frame = 2131361812;
			
			// aapt resource value: 0x7f0a0016
			public const int com_facebook_button_xout = 2131361814;
			
			// aapt resource value: 0x7f0a0012
			public const int com_facebook_fragment_container = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int com_facebook_login_activity_progress_bar = 2131361811;
			
			// aapt resource value: 0x7f0a0018
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131361816;
			
			// aapt resource value: 0x7f0a0017
			public const int com_facebook_tooltip_bubble_view_text_body = 2131361815;
			
			// aapt resource value: 0x7f0a0015
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131361813;
			
			// aapt resource value: 0x7f0a000d
			public const int display_always = 2131361805;
			
			// aapt resource value: 0x7f0a001c
			public const int imageView1 = 2131361820;
			
			// aapt resource value: 0x7f0a002d
			public const int imgFullscreen = 2131361837;
			
			// aapt resource value: 0x7f0a0048
			public const int imgPic = 2131361864;
			
			// aapt resource value: 0x7f0a0026
			public const int imgUploadPhoto = 2131361830;
			
			// aapt resource value: 0x7f0a0041
			public const int imgUploadedPhoto = 2131361857;
			
			// aapt resource value: 0x7f0a0007
			public const int inline = 2131361799;
			
			// aapt resource value: 0x7f0a000f
			public const int large = 2131361807;
			
			// aapt resource value: 0x7f0a000a
			public const int left = 2131361802;
			
			// aapt resource value: 0x7f0a004b
			public const int listAlbums = 2131361867;
			
			// aapt resource value: 0x7f0a0031
			public const int listView = 2131361841;
			
			// aapt resource value: 0x7f0a0047
			public const int messenger_send_button = 2131361863;
			
			// aapt resource value: 0x7f0a0033
			public const int myButton = 2131361843;
			
			// aapt resource value: 0x7f0a000e
			public const int never_display = 2131361806;
			
			// aapt resource value: 0x7f0a0010
			public const int normal = 2131361808;
			
			// aapt resource value: 0x7f0a0000
			public const int open_graph = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int page = 2131361793;
			
			// aapt resource value: 0x7f0a0035
			public const int profilePicMain = 2131361845;
			
			// aapt resource value: 0x7f0a002a
			public const int progressBar = 2131361834;
			
			// aapt resource value: 0x7f0a003c
			public const int progressBar1 = 2131361852;
			
			// aapt resource value: 0x7f0a000b
			public const int right = 2131361803;
			
			// aapt resource value: 0x7f0a0030
			public const int sample_content_fragment = 2131361840;
			
			// aapt resource value: 0x7f0a002f
			public const int sample_main_layout = 2131361839;
			
			// aapt resource value: 0x7f0a004d
			public const int search = 2131361869;
			
			// aapt resource value: 0x7f0a002b
			public const int sliding_tabs = 2131361835;
			
			// aapt resource value: 0x7f0a0011
			public const int small = 2131361809;
			
			// aapt resource value: 0x7f0a0005
			public const int standard = 2131361797;
			
			// aapt resource value: 0x7f0a0043
			public const int tableRow1 = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public const int tableRow2 = 2131361860;
			
			// aapt resource value: 0x7f0a0045
			public const int tableRow3 = 2131361861;
			
			// aapt resource value: 0x7f0a0042
			public const int tblBaseStrings = 2131361858;
			
			// aapt resource value: 0x7f0a0019
			public const int tbxAlbumTitle = 2131361817;
			
			// aapt resource value: 0x7f0a001f
			public const int tbxLoginPassword = 2131361823;
			
			// aapt resource value: 0x7f0a001b
			public const int tbxTags = 2131361819;
			
			// aapt resource value: 0x7f0a001e
			public const int tbxUserIdentifer = 2131361822;
			
			// aapt resource value: 0x7f0a002e
			public const int textView1 = 2131361838;
			
			// aapt resource value: 0x7f0a0008
			public const int top = 2131361800;
			
			// aapt resource value: 0x7f0a0038
			public const int txtCreateAccount = 2131361848;
			
			// aapt resource value: 0x7f0a0037
			public const int txtEmail = 2131361847;
			
			// aapt resource value: 0x7f0a0040
			public const int txtImgPath = 2131361856;
			
			// aapt resource value: 0x7f0a0027
			public const int txtName = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int txtNumber = 2131361832;
			
			// aapt resource value: 0x7f0a003a
			public const int txtOr = 2131361850;
			
			// aapt resource value: 0x7f0a0022
			public const int txtRegEmail = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int txtRegPassword = 2131361827;
			
			// aapt resource value: 0x7f0a0021
			public const int txtRegUsername = 2131361825;
			
			// aapt resource value: 0x7f0a0046
			public const int txtTest = 2131361862;
			
			// aapt resource value: 0x7f0a003e
			public const int txtViewImgBase64 = 2131361854;
			
			// aapt resource value: 0x7f0a0002
			public const int unknown = 2131361794;
			
			// aapt resource value: 0x7f0a002c
			public const int viewpager = 2131361836;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int com_facebook_activity_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_login_fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_tooltip_bubble = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_add_album = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_add_cameraPhoto = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_sign_up = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_sign_up1 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int fragment_sample = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int fullscreen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int home = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int homeNoScrollView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int messenger_button_send_blue_large = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int messenger_button_send_blue_round = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int messenger_button_send_blue_small = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int messenger_button_send_white_large = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int messenger_button_send_white_round = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int messenger_button_send_white_small = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int pager_item = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int row_contact = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int userAlbums = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int actionbar_home = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050012
			public const int ApplicationName = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int Hello = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int com_facebook_image_download_unknown_error = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_internet_permission_error_message = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_internet_permission_error_title = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_like_button_liked = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_like_button_not_liked = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_loading = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_loginview_cancel_action = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_loginview_log_in_button = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_loginview_log_in_button_long = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_loginview_log_out_action = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_loginview_log_out_button = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_loginview_logged_in_as = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_loginview_logged_in_using_facebook = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int com_facebook_send_button_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int com_facebook_share_button_text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int com_facebook_tooltip_default = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int fNamePlaceholder = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int facebook_app_id = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int messenger_send_button_text = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int openCamera = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int sample_hide_log = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int sample_show_log = 2131034133;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080017
			public const int CustomActionBarTheme = 2131230743;
			
			// aapt resource value: 0x7f080000
			public const int MessengerButton = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MessengerButton_Blue = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MessengerButton_Blue_Large = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int MessengerButton_Blue_Small = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int MessengerButton_White = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int MessengerButton_White_Large = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int MessengerButton_White_Small = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int MessengerButtonText = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int MessengerButtonText_Blue = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int MessengerButtonText_Blue_Large = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int MessengerButtonText_Blue_Small = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int MessengerButtonText_White = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int MessengerButtonText_White_Large = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int MessengerButtonText_White_Small = 2131230733;
			
			// aapt resource value: 0x7f080018
			public const int MyActionBar = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int Theme_Splash = 2131230742;
			
			// aapt resource value: 0x7f08000e
			public const int com_facebook_button = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int com_facebook_button_like = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int com_facebook_button_send = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int com_facebook_button_share = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int com_facebook_loginview_default_style = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int com_facebook_loginview_silver_style = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int dialog_animation = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int tooltip_bubble_text = 2131230740;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] com_facebook_like_view = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
